name = "watchexec"
version = "1.0.0"
gleam = ">= 1.14.0"
description = "Use watchexec as a cross-platform file event watcher on the BEAM"
licences = ["Apache-2.0"]

repository = { type = "github", user = "lpil", repo = "watchexec" }
links = [
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
sceall = ">= 1.1.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 2.3.2 and < 3.0.0"
